[tool.black]
include = '\.pyi?$'
extend-exclude = 'gui\/(.*\/)*ui_.*.py'
[tool.pdm]

[project]
name = "ssrando"
version = "1.3.2"
description = "Skyward Sword Randomizer"
authors = []
dependencies = [
    "nlzss11>=1.5",
    "PyYAML>=6.0",
    "PySide6>=6.4.3",
    "lark>=1.1.5",
    "toml>=0.10.2",
    "pyqtdarktheme>=2.1.0",
    "pyclip>=0.7.0",
    "matplotlib>=3.7.0",
    "opencv-python>=4.7.0.68",
    "numpy>=1.24.2",
]
requires-python = ">=3.9,<3.12"
readme = "README.md"
license = {text = "MIT"}
[project.optional-dependencies]
build = [
    "pyinstaller>=5.9.0",
]
dev = [
    "black>=23.1.0",
    "pytest>=7.2.2",
]

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"
