name: PR Build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup poetry
        run: python3 -mpip install poetry
      - name: Install dependencies
        run: poetry install
        env:
          POETRY_VIRTUALENVS_CREATE: false
      - name: Test if the formatting is correct
        run: python3 -mblack . --check
      - name: Build distribution
        run: python3 -mPyInstaller ssrando.spec
      - name: Run tests
        run: |
          python3 randoscript.py --noui --dry-run --seed=0
          cp -r logs logs_source
          dist/ssrando --noui --dry-run --seed=0
          diff logs logs_source
      - name: Make arc-replacements folder
        run: |
          mkdir -p dist/arc-replacements
          cp arc-replacements/README.md dist/arc-replacements
        shell: bash
      - name: Make models folder
        run: |
          mkdir -p dist/models
          cp models/README.md dist/models
        shell: bash
      - name: Copy Readme and changelog
        run: cp README.md CHANGELOG.md dist
        shell: bash
      - uses: SebRollen/toml-action@v1.2.0
        id: read_toml
        with:
          file: "pyproject.toml"
          field: "tool.poetry.version"
      - uses: actions/upload-artifact@v4
        with:
          name: Skyward Sword Randomizer v${{ steps.read_toml.outputs.value }}
          path: dist
