name: PR Build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install wheel
        run: python -m pip install wheel
      - name: Install requirements
        run: python -m pip install -r requirements.txt
      - name: Install dev requirements
        run: python -m pip install -r requirements_dev.txt
      - name: Test if the formatting is correct
        run: black . --target-version py310 --check
      - name: Install build requirements
        run: python -m pip install -r requirements_build.txt
      - name: Build distribution
        run: pyinstaller ssrando.spec
      - name: Run tests
        run: |
          python3 randoscript.py --noui --dry-run --seed=0
          cp -r logs logs_source
          dist/ssrando --noui --dry-run --seed=0
          diff logs logs_source
      - name: Make arc-replacements folder
        run: mkdir -p dist/arc-replacements
        shell: bash
      - name: Copy Readme and changelog
        run: cp README.md CHANGELOG.md dist
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          name: dist ${{ matrix.os }}
          path: dist
